name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-homelab-image .

      - name: Push Docker image to registry
        run: |
          # Example for Docker Hub (configure Docker Hub credentials in GitHub secrets)
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker tag my-homelab-image ${{ secrets.DOCKERHUB_USERNAME }}/my-homelab-image:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-homelab-image:latest

      - name: Deploy to homelab
        run: |
          # Example SSH-based deployment (configure SSH key in GitHub secrets)
          ssh -o StrictHostKeyChecking=no user@YOUR_HOMELAB_SERVER "
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-homelab-image:latest &&
          docker stop my-homelab-container || true &&
          docker rm my-homelab-container || true &&
          docker run -d --name my-homelab-container -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my-homelab-image:latest
          "
