name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-homelab-image .

      - name: Stop old container
        run: |
          docker stop my-homelab-container || true
          docker rm my-homelab-container || true

      - name: Run new container
        run: |
          docker run -d --name my-homelab-container -p 3000:3000 my-homelab-image
